### ISSUE TITLE
HomeAssistant integration

### ISSUE THREAD

**Issue by evilmumi** [frickelzeugs/FingerprintDoorbell#82]
Hi,

can anyone help to integrate to Homeassistant

**Comment by evilmumi** [comment]
> I have add this to my .yaml in HomeAssistant
> 
> ```
> sensor:
> #FingerprintDoorbell  
>   - state_topic: "/SmartHome/System/FingerprintDoorbell/matchName"
>     name: "FingerprintDoorbell matchName"
>   - state_topic: "/SmartHome/System/FingerprintDoorbell/matchId"
>     name: "FingerprintDoorbell matchId"
>   - state_topic: "/SmartHome/System/FingerprintDoorbell/ring"
>     name: "FingerprintDoorbell ring"
>         
> #Fingerprint Doorbell
> switch:
>   - unique_id: FingerprintDoorbell-IgnoreTouchRing
>     command_topic: /SmartHome/System/FingerprintDoorbell/ignoreTouchRing
>     payload_on: "off"
>     payload_off: "on"
>     name: "FingerprintDoorbell IgnoreTouchRing"
> ```

Thanks a lot.
I just added an automation but it calls every time.
How did you configure some?
```

alias: FingerprintDoorbell Name
description: ""
trigger:
  - platform: state
    entity_id:
      - sensor.fingerprint_name
    not_to: ""
condition:
  - condition: not
    conditions:
      - condition: state
        entity_id: sensor.fingerprint_name
        state: unavailable
      - condition: state
        entity_id: sensor.fingerprint_name
        state: unknown
action:
  - service: notify.alexa_media_room_dot
    data:
      message: Hello {{states('sensor.fingerprint_name')}} !
mode: single

```
